
package Frames;

import Clases.Agencia;
import Clases.CupoAgencia;
import Clases.ScrollSens;
import Clases.tools;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicSliderUI;

/**
 *
 * @author Cletox
 */
public class AgregarCupo extends javax.swing.JFrame {

   ArrayList<JCheckBox> programas = new ArrayList();
   ArrayList<JCheckBox> sorteos = new ArrayList();
   ArrayList<JCheckBox> agencias = new ArrayList();
   ArrayList<JCheckBox> animales = new ArrayList();
   ArrayList<Agencia> myAgencias = new ArrayList();
   Font segoui = new Font("Segoe UI",Font.PLAIN,15);
   
    public AgregarCupo() {
        initComponents();
        iniciar();
    }
     public AgregarCupo(ArrayList<Agencia> agencias) {
        initComponents();
        this.myAgencias=agencias;
        iniciar();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        panelAgencias = new javax.swing.JPanel();
        cbAgTodos = new javax.swing.JCheckBox();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAnimales = new javax.swing.JPanel();
        cbAnimalesTodos = new javax.swing.JCheckBox();
        scrollAnimales = new javax.swing.JScrollPane();
        panelProgramas = new javax.swing.JPanel();
        cbProgramaTodos = new javax.swing.JCheckBox();
        panelSorteos = new javax.swing.JPanel();
        cbSorteoTodos = new javax.swing.JCheckBox();
        c8am = new javax.swing.JCheckBox();
        c9am = new javax.swing.JCheckBox();
        c10am = new javax.swing.JCheckBox();
        c11am = new javax.swing.JCheckBox();
        c12pm = new javax.swing.JCheckBox();
        c1pm = new javax.swing.JCheckBox();
        c2pm = new javax.swing.JCheckBox();
        c3pm = new javax.swing.JCheckBox();
        c4pm = new javax.swing.JCheckBox();
        c5pm = new javax.swing.JCheckBox();
        c6pm = new javax.swing.JCheckBox();
        c7pm = new javax.swing.JCheckBox();
        panelMonto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fechaDesde = new com.toedter.calendar.JDateChooser();
        fechaHasta = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        cbAgTodos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbAgTodos.setText("Todas las Agencias");
        cbAgTodos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cbAgTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAgTodosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelAgenciasLayout = new javax.swing.GroupLayout(panelAgencias);
        panelAgencias.setLayout(panelAgenciasLayout);
        panelAgenciasLayout.setHorizontalGroup(
            panelAgenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAgTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAgenciasLayout.setVerticalGroup(
            panelAgenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAgTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTitulo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar cupos");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        cbAnimalesTodos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbAnimalesTodos.setText("Todos los animales");
        cbAnimalesTodos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cbAnimalesTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAnimalesTodosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelAnimalesLayout = new javax.swing.GroupLayout(panelAnimales);
        panelAnimales.setLayout(panelAnimalesLayout);
        panelAnimalesLayout.setHorizontalGroup(
            panelAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAnimalesTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollAnimales))
                .addContainerGap())
        );
        panelAnimalesLayout.setVerticalGroup(
            panelAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAnimalesTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cbProgramaTodos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbProgramaTodos.setText("Todos los Programas");
        cbProgramaTodos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cbProgramaTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProgramaTodosItemStateChanged(evt);
            }
        });
        cbProgramaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProgramaTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProgramasLayout = new javax.swing.GroupLayout(panelProgramas);
        panelProgramas.setLayout(panelProgramasLayout);
        panelProgramasLayout.setHorizontalGroup(
            panelProgramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgramasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbProgramaTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelProgramasLayout.setVerticalGroup(
            panelProgramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProgramasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbProgramaTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        cbSorteoTodos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbSorteoTodos.setText("Todos los sorteos");
        cbSorteoTodos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cbSorteoTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSorteoTodosItemStateChanged(evt);
            }
        });

        c8am.setBackground(new java.awt.Color(255, 255, 255));
        c8am.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c8am.setLabel("8 AM");
        c8am.setName(" 8 AM"); // NOI18N
        c8am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8amActionPerformed(evt);
            }
        });

        c9am.setBackground(new java.awt.Color(255, 255, 255));
        c9am.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c9am.setText(" 9 AM");
        c9am.setName("9 AM"); // NOI18N
        c9am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9amActionPerformed(evt);
            }
        });

        c10am.setBackground(new java.awt.Color(255, 255, 255));
        c10am.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c10am.setText(" 10 AM");
        c10am.setName("10 AM"); // NOI18N
        c10am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10amActionPerformed(evt);
            }
        });

        c11am.setBackground(new java.awt.Color(255, 255, 255));
        c11am.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c11am.setText(" 11 AM");
        c11am.setName("11 AM"); // NOI18N
        c11am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11amActionPerformed(evt);
            }
        });

        c12pm.setBackground(new java.awt.Color(255, 255, 255));
        c12pm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c12pm.setText(" 12 PM");
        c12pm.setName("12 PM"); // NOI18N
        c12pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12pmActionPerformed(evt);
            }
        });

        c1pm.setBackground(new java.awt.Color(255, 255, 255));
        c1pm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c1pm.setText(" 1 PM");
        c1pm.setName("1 PM"); // NOI18N
        c1pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1pmActionPerformed(evt);
            }
        });

        c2pm.setBackground(new java.awt.Color(255, 255, 255));
        c2pm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c2pm.setText(" 2 PM");
        c2pm.setName("2 PM"); // NOI18N
        c2pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2pmActionPerformed(evt);
            }
        });

        c3pm.setBackground(new java.awt.Color(255, 255, 255));
        c3pm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c3pm.setText(" 3 PM");
        c3pm.setName("3 PM"); // NOI18N
        c3pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3pmActionPerformed(evt);
            }
        });

        c4pm.setBackground(new java.awt.Color(255, 255, 255));
        c4pm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c4pm.setText(" 4 PM");
        c4pm.setName("4 PM"); // NOI18N
        c4pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4pmActionPerformed(evt);
            }
        });

        c5pm.setBackground(new java.awt.Color(255, 255, 255));
        c5pm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c5pm.setText(" 5 PM");
        c5pm.setName("5 PM"); // NOI18N
        c5pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5pmActionPerformed(evt);
            }
        });

        c6pm.setBackground(new java.awt.Color(255, 255, 255));
        c6pm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c6pm.setText(" 6 PM");
        c6pm.setName("6 PM"); // NOI18N
        c6pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6pmActionPerformed(evt);
            }
        });

        c7pm.setBackground(new java.awt.Color(255, 255, 255));
        c7pm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        c7pm.setText(" 7 PM");
        c7pm.setName("7 PM"); // NOI18N
        c7pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7pmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSorteosLayout = new javax.swing.GroupLayout(panelSorteos);
        panelSorteos.setLayout(panelSorteosLayout);
        panelSorteosLayout.setHorizontalGroup(
            panelSorteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSorteosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSorteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSorteoTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(panelSorteosLayout.createSequentialGroup()
                        .addGroup(panelSorteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c8am, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c9am, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c10am, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(c11am, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c12pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c1pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c2pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c3pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c4pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c5pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c6pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c7pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSorteosLayout.setVerticalGroup(
            panelSorteosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSorteosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbSorteoTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c8am)
                .addGap(8, 8, 8)
                .addComponent(c9am, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c10am)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c11am, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c12pm, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c1pm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2pm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3pm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c4pm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c5pm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c6pm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c7pm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Desde");

        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMontoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Monto del Cupo");

        fechaDesde.setDateFormatString("yyyy-MM-dd");
        fechaDesde.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        fechaHasta.setDateFormatString("yyyy-MM-dd");
        fechaHasta.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hasta");

        javax.swing.GroupLayout panelMontoLayout = new javax.swing.GroupLayout(panelMonto);
        panelMonto.setLayout(panelMontoLayout);
        panelMontoLayout.setHorizontalGroup(
            panelMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMontoLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(panelMontoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMonto)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMontoLayout.setVerticalGroup(
            panelMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMontoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addComponent(panelAgencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAnimales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSorteos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addComponent(panelProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAnimales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelAgencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSorteos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbProgramaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgramaTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProgramaTodosActionPerformed

    private void cbProgramaTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProgramaTodosItemStateChanged
       if(cbProgramaTodos.isSelected()){
           for(JCheckBox programa : programas){
               programa.setSelected(true);
           }
       }
    }//GEN-LAST:event_cbProgramaTodosItemStateChanged

    private void cbAgTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAgTodosItemStateChanged
      if(cbAgTodos.isSelected()){
           for(JCheckBox agencia : agencias){
               agencia.setSelected(true);
           }
       }
    }//GEN-LAST:event_cbAgTodosItemStateChanged

    private void c8amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8amActionPerformed
       
    }//GEN-LAST:event_c8amActionPerformed

    private void c9amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9amActionPerformed
        
    }//GEN-LAST:event_c9amActionPerformed

    private void c10amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10amActionPerformed
       
    }//GEN-LAST:event_c10amActionPerformed

    private void c11amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11amActionPerformed
        
    }//GEN-LAST:event_c11amActionPerformed

    private void c12pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12pmActionPerformed
       
    }//GEN-LAST:event_c12pmActionPerformed

    private void c1pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1pmActionPerformed
       
    }//GEN-LAST:event_c1pmActionPerformed

    private void c2pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2pmActionPerformed
        
    }//GEN-LAST:event_c2pmActionPerformed

    private void c3pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3pmActionPerformed
       
    }//GEN-LAST:event_c3pmActionPerformed

    private void c4pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4pmActionPerformed
       
    }//GEN-LAST:event_c4pmActionPerformed

    private void c5pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5pmActionPerformed
        
    }//GEN-LAST:event_c5pmActionPerformed

    private void c6pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6pmActionPerformed
       
    }//GEN-LAST:event_c6pmActionPerformed

    private void c7pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7pmActionPerformed
        
    }//GEN-LAST:event_c7pmActionPerformed

    private void cbSorteoTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSorteoTodosItemStateChanged
      if(cbSorteoTodos.isSelected()){
           for(JCheckBox sorteo : sorteos){
               sorteo.setSelected(true);
           }
       }
    }//GEN-LAST:event_cbSorteoTodosItemStateChanged

    private void cbAnimalesTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAnimalesTodosItemStateChanged
      if(cbAnimalesTodos.isSelected()){
           for(JCheckBox animal : animales){
               animal.setSelected(true);
           }
       }
     
    }//GEN-LAST:event_cbAnimalesTodosItemStateChanged

    private void txtMontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyPressed
      
    }//GEN-LAST:event_txtMontoKeyPressed

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
      new tools().soloNumerosyCantidadDigitos(evt, txtMonto, 1);
    }//GEN-LAST:event_txtMontoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(!validarCamposVacios()){
          JOptionPane.showMessageDialog(panelMonto, "Debe seleccionar al menos:\n"
                  + " A) 1 Agencia\n"
                  + " B) 1 Sorteo\n"
                  + " C) 1 Programa\n"
                  + " D) 1 Animal\n"
                  + " E) Ingresar el monto\n\n"
                  + "Si no cumple con eso no podrá continuar");
      }else{
          double monto = Double.parseDouble(txtMonto.getText());
          String programaSeleccionado = getProgramasSeleccionadas();
          String animalesSeleccionado = getAnimalesSeleccionadas();
          String sorteosSeleccionados = getSorteosSeleccionadas();
          String fechaDesde = getFechaDesde();
          String fechaHasta = getFechaHasta();
          
          System.out.println("programaSeleccionado: "+programaSeleccionado);
          System.out.println("animalesSeleccionado: "+animalesSeleccionado);
          System.out.println("sorteosSeleccionados: "+sorteosSeleccionados);
          
          
          for(JCheckBox agenc : agencias){
            if(agenc.isSelected()){
                int idAgencia = Integer.parseInt(agenc.getName());
                new CupoAgencia().insertCupo(
                        idAgencia,
                        "Especifico",
                        monto, 
                        fechaDesde,
                        fechaDesde,
                        programaSeleccionado,
                        sorteosSeleccionados,
                        animalesSeleccionado
                );
            }
          }
          JOptionPane.showMessageDialog(panelMonto, "Información agregada con éxito");
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String getAgenciasSeleccionadas(){
        String agenciaSeleccionada ="";
              for(JCheckBox agenc : agencias){
                  if(agenc.isSelected())
                  agenciaSeleccionada+=agenc.getName()+",";
              }agenciaSeleccionada = agenciaSeleccionada.substring(0, agenciaSeleccionada.length()-1);
              
          return agenciaSeleccionada;
    }
    
    private String getProgramasSeleccionadas(){
        String programaSeleccionado = "Todos";
          if(programas.stream().filter(a->a.isSelected()).count()<programas.size()){
              programaSeleccionado="";
              for(JCheckBox program : programas){
                  if(program.isSelected())
                  programaSeleccionado+=program.getText()+",";
              }programaSeleccionado = programaSeleccionado.substring(0, programaSeleccionado.length()-1);
          }
          return programaSeleccionado;
    }
    
    private String getAnimalesSeleccionadas(){
        String animalesSeleccionado = "Todos";
          if(animales.stream().filter(a->a.isSelected()).count()<animales.size()){
              animalesSeleccionado="";
              for(JCheckBox animal : animales){
                  if(animal.isSelected())
                  animalesSeleccionado+=animal.getText()+",";
              }animalesSeleccionado = animalesSeleccionado.substring(0, animalesSeleccionado.length()-1);
          }
          return animalesSeleccionado;
    }
    
    private String getSorteosSeleccionadas(){
        String sorteosSeleccionados = "Todos";
          if(sorteos.stream().filter(a->a.isSelected()).count()<sorteos.size()){
              sorteosSeleccionados="";
              for(JCheckBox sorteo : sorteos){
                   if(sorteo.isSelected())
                  sorteosSeleccionados+=sorteo.getText().trim().toLowerCase().replace(" ", "")+",";
              }sorteosSeleccionados = sorteosSeleccionados.substring(0, sorteosSeleccionados.length()-1);
          }
          return sorteosSeleccionados;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c10am;
    private javax.swing.JCheckBox c11am;
    private javax.swing.JCheckBox c12pm;
    private javax.swing.JCheckBox c1pm;
    private javax.swing.JCheckBox c2pm;
    private javax.swing.JCheckBox c3pm;
    private javax.swing.JCheckBox c4pm;
    private javax.swing.JCheckBox c5pm;
    private javax.swing.JCheckBox c6pm;
    private javax.swing.JCheckBox c7pm;
    private javax.swing.JCheckBox c8am;
    private javax.swing.JCheckBox c9am;
    private javax.swing.JCheckBox cbAgTodos;
    private javax.swing.JCheckBox cbAnimalesTodos;
    private javax.swing.JCheckBox cbProgramaTodos;
    private javax.swing.JCheckBox cbSorteoTodos;
    private com.toedter.calendar.JDateChooser fechaDesde;
    private com.toedter.calendar.JDateChooser fechaHasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelAgencias;
    private javax.swing.JPanel panelAnimales;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelMonto;
    private javax.swing.JPanel panelProgramas;
    private javax.swing.JPanel panelSorteos;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollAnimales;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

     public String getAnimal(int numero) {
        String animal = "";

        if (true) {
            switch (numero) {
                case 0:
                    animal = "Delfin";
                    break;
                case -1:
                    animal = "Ballena";
                    break;
                case 1:
                    animal = "Carnero";
                    break;
                case 2:
                    animal = "Toro";
                    break;
                case 3:
                    animal = "Ciempies";
                    break;
                case 4:
                    animal = "Alacrán";
                    break;
                case 5:
                    animal = "Leon";
                    break;
                case 6:
                    animal = "Rana";
                    break;
                case 7:
                    animal = "Perico";
                    break;
                case 8:
                    animal = "Ratón";
                    break;
                case 9:
                    animal = "Aguila";
                    break;
                case 10:
                    animal = "Tigre";
                    break;
                case 11:
                    animal = "Gato";
                    break;
                case 12:
                    animal = "Caballo";
                    break;
                case 13:
                    animal = "Mono";
                    break;
                case 14:
                    animal = "Paloma";
                    break;
                case 15:
                    animal = "Zorro";
                    break;
                case 16:
                    animal = "Oso";
                    break;
                case 17:
                    animal = "Pavo";
                    break;
                case 18:
                    animal = "Burro";
                    break;
                case 19:
                    animal = "Chivo";
                    break;
                case 20:
                    animal = "Cochino";
                    break;
                case 21:
                    animal = "Gallo";
                    break;
                case 22:
                    animal = "Camello";
                    break;
                case 23:
                    animal = "Cebra";
                    break;
                case 24:
                    animal = "Iguana";
                    break;
                case 25:
                    animal = "Gallina";
                    break;
                case 26:
                    animal = "Vaca";
                    break;
                case 27:
                    animal = "Perro";
                    break;
                case 28:
                    animal = "Zamuro";
                    break;
                case 29:
                    animal = "Elefante";
                    break;
                case 30:
                    animal = "Caimán";
                    break;
                case 31:
                    animal = "Lapa";
                    break;
                case 32:
                    animal = "Ardilla";
                    break;
                case 33:
                    animal = "Pescado";
                    break;
                case 34:
                    animal = "Venado";
                    break;
                case 35:
                    animal = "Jirafa";
                    break;
                case 36:
                    animal = "Culebra";
                    break;
            }
        }
        return animal;
    }
    
    private void iniciar() {
        if(myAgencias.isEmpty()){
            myAgencias = (ArrayList) new Agencia().listarAgencias().clone();
        }
        
        fechaDesde.setDate(new Date());
        fechaHasta.setDate(new Date());
        
        new ScrollSens(scrollAnimales,40);
        panelProgramas.setLayout(new BoxLayout(panelProgramas, BoxLayout.Y_AXIS));
        panelAgencias.setLayout(new BoxLayout(panelAgencias, BoxLayout.Y_AXIS));
        panelSorteos.setLayout(new BoxLayout(panelSorteos, BoxLayout.Y_AXIS));
        panelAnimales.setLayout(new BoxLayout(panelAnimales, BoxLayout.Y_AXIS));
        
        panelProgramas.setSize(220, panelProgramas.getHeight());
        panelAgencias.setSize(220, panelAgencias.getHeight());
        panelSorteos.setSize(220, panelSorteos.getHeight());
        panelAnimales.setSize(220, panelAnimales.getHeight());
        
        agregarProgramas();
        agregarAgencias();
        agregarSorteos();
        agregarAnimales();
    }
    private void agregarProgramas(){
        ActionListener listener = e -> {
            cbProgramaTodos.setSelected(
                    programas.stream()
                    .filter(
                        p ->p.isSelected()
                    ).count() == programas.size() ? true : false
                );
        };
        
        
        JCheckBox lottoActivo = new JCheckBox();
        lottoActivo.setText("LottoActivo");
        lottoActivo.setName("LottoActivo");
        lottoActivo.addActionListener(listener);
        lottoActivo.setFont(segoui);
        programas.add(lottoActivo);
        
        JCheckBox granjita = new JCheckBox();
        granjita.setText("Granjita");
        granjita.setName("Granjita");
        granjita.addActionListener(listener);
        granjita.setFont(segoui);
        programas.add(granjita);
        
        
        panelProgramas.add(lottoActivo);
        panelProgramas.add(granjita);
    }
   
    private void agregarAgencias(){
         ActionListener listener = e -> {
            cbAgTodos.setSelected(
                    agencias.stream()
                    .filter(
                        p ->p.isSelected()
                    ).count() == agencias.size() ? true : false
                );
        };
         
         for(Agencia agencia:myAgencias){
             JCheckBox temp = new JCheckBox();
             temp.setName(agencia.getId()+"");
             temp.setText(agencia.getNombreAgencia());
             temp.addActionListener(listener);
             temp.setFont(segoui);
             agencias.add(temp);
             panelAgencias.add(temp);
         }
    }
    
    private void agregarSorteos(){
        sorteos.add(c8am);
        sorteos.add(c9am);
        sorteos.add(c10am);
        sorteos.add(c11am);
        sorteos.add(c12pm);
        sorteos.add(c1pm);
        sorteos.add(c2pm);
        sorteos.add(c3pm);
        sorteos.add(c4pm);
        sorteos.add(c5pm);
        sorteos.add(c6pm);
        sorteos.add(c7pm);
        
         ActionListener listener = e -> {
            cbSorteoTodos.setSelected(
                    sorteos.stream()
                    .filter(
                        p ->p.isSelected()
                    ).count() == sorteos.size() ? true : false
                );
        };
        for(JCheckBox sorteo:sorteos){
            sorteo.addActionListener(listener);
            sorteo.setFont(segoui);
            panelSorteos.add(sorteo);
        }
    }
    
    private void agregarAnimales(){
        JPanel panelAnimalesx = new JPanel();
        ActionListener listener = e -> {
            cbAnimalesTodos.setSelected(
                    animales.stream()
                    .filter(
                        p ->p.isSelected()
                    ).count() == animales.size() ? true : false
                );
        };
        
        JCheckBox ballena = new JCheckBox();
        ballena.setText("00Ballena");
        ballena.setName("00");
        ballena.addActionListener(listener);
        ballena.setFont(segoui);
        
        animales.add(ballena);
        panelAnimalesx.add(ballena);
        
        panelAnimalesx.setLayout(new BoxLayout(panelAnimalesx, BoxLayout.Y_AXIS));
        for (int i = 0; i < 37; i++) {
            JCheckBox temp = new JCheckBox();
            temp.setName(i+"");
            temp.setText(i+getAnimal(i));
            temp.addActionListener(listener);
            temp.setFont(segoui);
            
            panelAnimalesx.add(temp);
            animales.add(temp);
        }
        panelAnimalesx.setSize(panelAnimales.getWidth()-10, 500);
        scrollAnimales.setViewportView(panelAnimalesx);
    }

    private boolean validarCamposVacios() {
         return agencias.stream().filter(a-> a.isSelected()).count()>0 &&
                programas.stream().filter(p-> p.isSelected()).count()>0 && 
                 animales.stream().filter(a-> a.isSelected()).count()>0 &&
                 sorteos.stream().filter(s-> s.isSelected()).count()>0 &&
                 !txtMonto.getText().isEmpty();
    }
    public String getFechaDesde(){
        return new SimpleDateFormat("yyyy-MM-dd").format(fechaDesde.getDate());
    }
    public String getFechaHasta(){
        return new SimpleDateFormat("yyyy-MM-dd").format(fechaHasta.getDate());
    }
}
